- name: HTML
  logo: html5
  color: '#F16529'
  url: 'https://www.w3schools.com/html/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/webportfolio'

- name: PHP
  logo: php
  color: '#777BB3'
  url: 'https://www.php.net/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock'   
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    
- name: JavaScript
  logo: javascript
  color: '#F0DB4F'
  url: 'https://www.w3schools.com/js/default.asp'
  projects:
    - url: 'https://github.com/jaborjkath/hello-open-source'
    - url: 'https://github.com/jaborjkath/nextjs-boilerplate'    
    - url: 'https://github.com/jaborjkath/timeclock'
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    
- name: jQuery
  logo: jquery
  color: '#0868AC'
  url: 'https://jquery.com/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/timeclock'    

- name: Vercel
  logo: vercel
  color: '#000000'
  url: 'https://vercel.com/'
  projects:
    - url: 'https://github.com/jaborjkath/webportfolio'
    
- name: Java
  logo: java
  color: '#5382a1'
  url: 'https://www.java.com/'
  projects:
    - url: 'https://github.com/jaborjkath/seleniumproj'

- name: Gen AI
  logo: genai
  color: '#74AA9C'
  url: 'https://coursera.org/share/05d9dcafa5c7ca67a9a4b2d47b07ecbd'
  projects:
    - url: 'https://github.com/jaborjkath/eclinic-scheduler'    
    
- name: Figma
  logo: figma
  color: '#ff7262'
  url: 'https://www.figma.com/'
  projects:
    - url: 'https://github.com/jaborjkath/little-lemon-app'

- name: Canva
  logo: canva
  color: '#016FB6'
  url: 'https://www.canva.com/'
  projects:
    - url: 'https://github.com/jaborjkath/canva-digiprod-set'
