- name: HTML
  logo: html5
  color: '#F16529'
  url: 'https://www.w3schools.com/html/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/webportfolio'

- name: PHP
  logo: php
  color: '#777BB3'
  url: 'https://www.php.net/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock'   
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    
- name: JavaScript
  logo: javascript
  color: '#F0DB4F'
  url: 'https://www.w3schools.com/js/default.asp'
  projects:
    - url: 'https://github.com/jaborjkath/hello-open-source'
    - url: 'https://github.com/jaborjkath/nextjs-boilerplate'    
    - url: 'https://github.com/jaborjkath/timeclock'
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    
- name: jQuery
  logo: jquery
  color: '#0868AC'
  url: 'https://jquery.com/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/timeclock'    

- name: Java
  logo: java
  color: '#5382a1'
  url: 'https://www.java.com/'
  projects:
    - url: 'https://github.com/jaborjkath/seleniumproj'

- name: Figma
  logo: figma
  color: '#ff7262'
  url: 'https://www.figma.com/'
  projects:
    - url: [Little Lemon] (https://www.figma.com/proto/lY7IGcv7IYjF7OjSXwaV8s/Final-UX%2FUI-Project---Little-Lemon---Prototype?type=design&node-id=1-45&t=ZzMWbMwSY3SdlwH2-1&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A45&mode=design)
