- name: HTML
  logo: html5
  color: '#F16529'
  url: 'https://www.w3schools.com/html/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/webportfolio'

- name: PHP
  logo: php
  color: '#777BB3'
  url: 'https://www.php.net/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock'   

- name: JavaScript
  logo: javascript
  color: '#F0DB4F'
  url: 'https://www.w3schools.com/js/default.asp'
  projects:
    - url: 'https://github.com/jaborjkath/hello-open-source'
    - url: 'https://github.com/jaborjkath/nextjs-boilerplate'    
    - url: 'https://github.com/jaborjkath/timeclock'
    - url: 'https://github.com/jaborjkath/timeclock_assignment'
    - url: 'https://github.com/jaborjkath/old_work_exercises' 
