- name: HTML
  logo: html5
  color: '#F16529'
  url: 'https://www.w3schools.com/html/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock-namesearch'
    - url: 'https://github.com/jaborjkath/webportfolio'

- name: PHP
  logo: php
  color: '#777BB3'
  url: 'https://www.php.net/'
  projects:
    - url: 'https://github.com/jaborjkath/timeclock'   
